### ISSUE TITLE
Old Linux kernel images are left on /boot

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#1]
I noticed that after running all those remove linux commands, the old linux images are still there on /boot. A `sudo vkpurge rm all` would be nice to get rid of leftovers from past linux kernels.

**Comment by drake-newell** [comment]
I think in addition to this, I'll have vkpurge-libre installed in ~/.local/bin for future kernel management with linux-libre (the `cut` command in the original vkpurge script causes issues with the format of the linux-libre images in /boot), maybe with a yes/no prompt as you have suggested in #2.

**Comment by drake-newell** [comment]
Fixed this.
