### ISSUE TITLE
Adds ignore multiple times

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#14]
Tried the liberation script yesterday and it was very satisfying to use this time. Love it! I was able to run it on a tty just fine and the questions were very helpful on the way.

One thing I noticed is that it adds the ignore line to `/etc/xbps.d/10-ignore.conf` multiple times. So I was [wrong](https://www.reddit.com/r/voidlinux/comments/fy6gyi/is_it_possible_to_manually_install_the_linuxlibre/fziujic/) about the `sudo tee -a ...`. It should be `sudo tee ...` so that it doesn't append to the file (instead replaces it).

So,
```
echo "ignorepkg=linux" | sudo tee -a /etc/xbps.d/10-ignore.conf
```

should be:
```
echo "ignorepkg=linux" | sudo tee /etc/xbps.d/10-ignore.conf
```

**Comment by drake-newell** [comment]
Fixed it.
