### ISSUE TITLE
[LIST] Which packages do you want to see liberated first?

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#16]
As you may know we have [~200 minor packages](https://github.com/drake-newell/void-packages/issues/8#issue-668082198) to liberate. [[list](https://gist.github.com/reback00/165f8225e0354ec3ff80a4f2e10839b1)] It's a lot, but hey, we have to start somewhere, right?

1. Mention which programs get most caught with the `your-freedom` package.
2. Or just mention which one(s) you're interested to see liberated first from this [list](https://gist.github.com/reback00/165f8225e0354ec3ff80a4f2e10839b1).

My list is as follows:

```
abiword, cdrtools, engrampa, font-bh-ttf, grub, kio, kodi, libxfce4ui, p7zip, unzip
```

**Comment by drake-newell** [comment]
The main one I want to liberate is texlive-bin/the other texlive packages in that list and acpi-call, plus those you've listed.

**Comment by reback00** [comment]
@drake-newell  Well, I haven't used them myself. So feel free to correct me.

- `texlive-bin` is kind of like a meta package on Void. It actually makes the path of actual texlive version installed to be available in `$PATH`. The actual texlive package is on separate package, such as `texlive2019-bin`, `texlive2020-bin`. I've looked into [`texlive2020-bin`](https://github.com/void-linux/void-packages/tree/master/srcpkgs/texlive2020-bin). Although it does not have "Arch Linux" branding the way Arch package has, but it does have mentions of "Void Linux" and "void" for a file called [`void.profile`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/texlive2020-bin/files/void.profile). <br/><br/> Void Linux is not 100% libre. So, to be strictly libre I guess we can change these instances to `Void Libre` or something? Is the name `Void Libre` ok to be used for this project?

- `acpi_call-dkms` has dependencies of "linux-headers" on [Arch](https://www.archlinux.org/packages/community/x86_64/acpi_call-dkms/) which has been changed to "linux-libre-headers" on [Parabola](https://git.parabola.nu/abslibre.git/tree/libre/acpi_call-dkms/PKGBUILD). Void package template does not mention "linux-headers", so I guess we can pass it as libre. <br/><br/>As a sidenote, this makes me think if we should distinguish the packages that are already libre in a different manner? Because we would tend to build all of them listed on allowlist.txt. But that's not necessary if they're already libre. That's why I opened #19.

**Comment by drake-newell** [comment]
@reback00 I'm not exactly sure about a name that includes the name Void. Michael Aldridge, one of the void contributors, was in the fosshost irc and suggested that we not use the word void because it is not affiliated with it. I can ask him about it specifically though.

**Comment by reback00** [comment]
@drake-newell  I think he is right. It seems as if we are official part of the void team. In that case I think we should decide for a new name. I've opened a separate issue to discuss: #21
