### ISSUE TITLE
Yes/no prompt is needed

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#2]
A y/n prompt is needed in many cases, like if it should create `~/.local/src`, if it should remove linux packages and their images on `/boot`, if it should install your-freedom etc. This would be much more interactive and would involve less manual intervention by the user.

**Comment by drake-newell** [comment]
I've never done something like that in a script but I l know it has something to do with the `read` command. I'll look into it.

**Comment by drake-newell** [comment]
I added this feature, although it is pretty messy for now.
