### ISSUE TITLE
Project needs a name that does not have the word "Void"

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#21]
> @reback00 I'm not exactly sure about a name that includes the name Void. Michael Aldridge, one of the void contributors, was in the fosshost irc and suggested that we not use the word void because it is not affiliated with it. ... [source](https://github.com/drake-newell/void-packages/issues/16#issuecomment-671177858)

Since the project utilizes packages from Void, I thought it would be a good idea to keep a name that starts with "V". I have looked into some dictionary words that start with "v":

```
victory
volt
velocity
verso
valid
velvet
```

I've also looked into [tech words](https://www.techopedia.com/it-terms/v) starting with V, but not sure if anything is suitable.

The one I'm most positive about is:

voice - It's the closest to "Void", starts with V and moderately short. I was also thinking if we can shorten it to "voic" or "voiz" (weird shortening trends these days, such as Wickr, Vultr, Swvl etc.) On that note, the word "voice" in Romanian language is "voce".

We'd also have to get a domain someday. Unfortunately I could not find most of these available as .com, .org domain names, even modified ones (voic, voce, voiz etc.) We would probably have to append something like "linux" or "libre" or something. Another option would be look into options like .live, .site, .xyz, .online domains. e.g. "voic.site", "voice.site" etc. are available.

But feel free to suggest and discuss.

**Comment by drake-newell** [comment]
I've always been a fan of various ancient mythologies. When I think of the word "Void," I'm reminded of all of the various pre-creation primordial voids in Greek, Norse, etc. mythologies. In Greek mythology, that would be Chaos or Kháos. In Norse, it would be Ginnungagap. Alternatively, we could call it Ymir after the ice giant that the world was formed from out of the void. In Egyptian mythology, Kek is the god of chaos and darkness, Nu is the personification of the ancient void, and Apophis is the snake that wants to devour the world and plunge it into chaos/an eternal abyss. So I guess any of those are possible names that reference a void while also being different.

**Comment by reback00** [comment]
> When I think of the word "Void," I'm reminded of all of the various pre-creation primordial voids in Greek, Norse, etc. mythologies. ...So I guess any of those are possible names that reference a void while also being different.

WOW. I never knew "void" was related to Greek mythology. Great idea. My vote goes to "Nu". It's short, simple and yet somehow fits into the weird spelling trend (close to "New"). If someday we can have our own distro, we can call Nu OS. `nu.site` is also available (yaaayyy!)

**Comment by drake-newell** [comment]
@reback00 My personal favorite is Chaos if only because it sounds cool, but we can discuss these options further

**Comment by reback00** [comment]
Chaos is great too. It was my second choice. But a quick web search told me that an OS with the same name already [exists](https://en.wikipedia.org/wiki/CHAOS_(Linux_distribution)).

There is also a project called ["N/u Linux"](https://sourceforge.net/projects/n-u-linux/). While it's "N/u", not "Nu" I think it can cause confusion. But would love to hear your thoughts. Searched others as well:

- "[__Ymir__](https://store.steampowered.com/app/378360/Ymir/) is a 4X multiplayer strategy game combined with a city builder where each player develops a civilization of Pigmen starting at the stone age."
- "[__Ginnungagap__](https://en.wikipedia.org/wiki/Ginnungagap) is featured in the Marvel Universe" I don't know if that's going to get us into trouble for using that. But besides that the name is a bit lengthy and would be hard to type or pronounce.
- It's not directly __Apophis__, but a project named [__Apophysis__](https://sourceforge.net/projects/apophysis/) exists. I'm not too positive about it though because it would be hard to type. But better than "Ginnungagap" I guess. :) EDIT: there's an [app](https://play.google.com/store/apps/details?id=apophis.internet.radio&hl=en_US) with the name
- Found a software related [page](https://www-project.slac.stanford.edu/lc/atf/software.html) with __KEK__ on title but not sure if it's a problem. __KEK__ is also a [term](https://crypto.stackexchange.com/questions/39910/what-is-kek-and-how-is-used-for-key-sharing) related to encryption/aes.

EDIT: Searched my suggestions as well:

- victory - there's a [theme](https://www.ubuntufree.com/download-victory-theme/) for Ubuntu with the name
- volt - there's an [app](https://volt-app.com/) with the name
- velocity - there's a [company](http://velocitysoftware.com/) who specializes in Linux
- verso - there's an [app](https://app.versoapp.com/)
- valid - there's an [app](https://play.google.com/store/apps/details?id=com.intesigroup.time4eid.app&hl=en)
- velvet - there's an [app](https://www.thevelvetapp.com/)
- voice - there's an [app](https://www.nbc.com/the-voice/exclusives/voice-app)
- voic - there's an [app](https://apps.apple.com/us/app/voic-ee-crowdpolling/id1161398315)
- voce - there's an [app](https://www.voceapp.com/)
- voiz - there's an [app](http://thevoizapp.tech/)

**Comment by drake-newell** [comment]
@reback00 tbh I think Ymir might be the best because it's seems the least confusing and makes sense BC he came out of the void, and this project involves transforming void into a libre os.

**Comment by reback00** [comment]
> @reback00 tbh I think Ymir might be the best because it's seems the least confusing and makes sense BC he came out of the void, and this project involves transforming void into a libre os.

@drake-newell I understand. I had some liking to it too as a short name. But there's a game [already](https://ymir.gamepedia.com/YMIR) with that name.

> "Ymir is a 4X multiplayer strategy game combined with a city builder where each player develops a civilization of Pigmen starting at the stone age."

And worst of all, it's proprietary. So we shouldn't use the name. If we mention it in our packages, it will go against GNU philosophies.

**Comment by drake-newell** [comment]
@reback00 I mean it looks like all of the names share it with something else. I think Ymir works best specifically because it is not shared with another free-software/Linux project, creating the lowest amount of confusion. It's not like this game has a monopoly on the word.

**Comment by reback00** [comment]
Well, I searched and found some trademarks on that name on [uspto.gov](http://tmsearch.uspto.gov/) and [gov.uk](https://www.gov.uk/search-for-trademark). Then searched some more to see if trademarks can be a problem. Found out that if the trademarks are not in the same industry it's not an issue. I found a trademark related to [clothing](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4805:ik02u3.2.1). Plus, trademarks are less to be a risk for non-profit projects. So we're clear on "Ymir" on that side. But the issue remains on the Free Software side.

Although I agree on the idea of using mythology names that derive from "Void", I would urge you to not use the "Ymir" name directly. Because it's the name of a closed source program which goes against the Free Software movement.

But there's a way! As I was reading about trademarks and naming new open source projects I found [fossmarks.org](https://fossmarks.org/post/). They have a wonderful short guide to help in the naming process. They have some [amazing tips](https://fossmarks.org/post/2choosingname/) about how similar names can be avoided with some simple tricks. Who knows, we may find a name with those tips that lets us use our favorite picks (Chaos, Nu, Ymir), with some clever variations. (NuChaos, Eemir, Yemir, Chymir, Numir - web search revealed they are all available to use and trademark-free. If we try together, I'm sure we can find some more like this.)

This is not exactly our picks directly, but searching around for the last couple of days made me frustrated at how scarce known words have become to be available on the tech sphere, even misspelled ones. So we have no other way but to go this way to stay safe and remain unique.

EDIT: One of the articles suggested using a [business name generator](https://duckduckgo.com/?q=business+name+generator&ia=web). We can try that if all things fail.

**Comment by drake-newell** [comment]
@reback00 I still don't understand why using the same name as some random game is against the free software philosophy? How does that violate anyone's freedom or the GPL?

**Comment by reback00** [comment]
@drake-newell GNU project does not support mentioning names of nonfree/proprietary software because it advertises their names to users. e.g. a quote from [GNU website guidelines](https://www.gnu.org/server/standards/gnu-website-guidelines.html):

> When proprietary software is promoted, people get the impression that it is okay to use it, while we are trying to convince them otherwise. As such, we avoid offering such free advertising, either directly on our site or indirectly through links. What's tricky about this criteria is the “promotion” point: there's a difference between mentioning proprietary software and making a sales pitch for it. Indeed, the GNU Project website mentions proprietary software throughout, but never gives people the impression that its use does not present ethical problems.

It would be incompatible with our effort to use a name of a nonfree software as a project name. We are removing mentions of nonfree software from our packages, like Parabola did. But if we name our own project the same with a nonfree software, it goes against this goal.

Some points to take here:

- In the whole GNU website I have never seen any name of nonfree software other than to point out it's bad for users.
- Parabola has done considerable amount of work to remove mentions of names of nonfree services and software from their package source code. ([example](https://git.parabola.nu/abslibre.git/tree/libre/minitube/remove_unfree_recommendations.patch), #12 has screenshots of what it does) I assume they have done it to abide by Free Software movement. I can be wrong. If so, I would like to know why would they do it otherwise.
- Debian is not considered 100% Free Software because they have a repo of nonfree drivers (which is not even enabled by default, available as an option but still not acceptable by GNU/FSF). I would imagine it means something.
- The [Free System Distribution Guidelines](https://www.gnu.org/distros/free-system-distribution-guidelines.html) says to avoid using confusing names similar to of nonfree distros:
> We will not list a distribution whose name makes confusion with nonfree distributions likely. For example, if Foobar Light is a free distribution and Foobar is a nonfree distribution, we will not list Foobar Light. This is because __we expect that the distinction between the two would be lost in the process of communicating the message.__

- The name "Ymir" is totally acceptable for any distro, plus, it is your project mainly. You can name it what you feel is right and lawful to you. But it won't be a 100% Free Software / [Free distro](https://www.gnu.org/distros/free-system-distribution-guidelines.html), ever. I may be wrong, of course. But I think you can contact GNU about this if you wish to be sure.

EDIT: added mention of #12

**Comment by drake-newell** [comment]
@reback00 I think it would still be 100% libre. If Parabola is libre, then this would be as well. There happens to be a task automation service called Parabola that is closed source (parabola.io). This does not make Parabola nonfree. I would say that there is a difference between sharing a name with something and making a reference to the thing whose name is shared. We are not making a libre fork of this "Ymir" game, nor are we referencing it.

**Comment by reback00** [comment]
Well, parabola.io may have started around [2016](https://web.archive.org/web/*/https://parabola.io/) and GNU Parabola has an initial release in [2009](https://en.wikipedia.org/wiki/Parabola_GNU/Linux-libre). So when they chose this name, parabola.io was not around. I believe if it was around, they would've avoided this name.

**Comment by drake-newell** [comment]
@reback00 Also, I'll go back to what I've said before - The game "Ymir" is not a distro, so the naming part of the GNU guidelines doesn't apply.  Also, this isn't even a complete distro, so it wouldn't meet those guidelines anyway.
