### ISSUE TITLE
Nonfree packages can be searched for

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#29]
On our current install of Ymir, nonfree packages can be searched for. e.g. Running `xbps-query -Rs firefox` shows firefox/firefox-esr packages which are non-free.

`your-freedom` will not let the user install them by mistake. But ideally nonfree packages should not appear on search results.

**Comment by drake-newell** [comment]
Do you mean packages from the nonfree repo? Because that does not happen in my case. If you mean nonfree packages in the free repo, I'm afraid that as long as we use void's repos for the majority of packages, which are free, we can't really avoid that as far as I can tell.
EDIT: one possible solution is switching over fully to our repo by partially mirroring void's packages with rsync, minus the nofree subrepo

**Comment by reback00** [comment]
I meant Void's repo. We can't really ignore Void's repo, because it will be an overhead to build **all** the packages from Void's repo. I was thinking if we could modify `xbps-query` to ignore nonfree packages from our your-freedom denylist to show up on search results.

**Comment by drake-newell** [comment]
> I meant Void's repo. We can't really ignore Void's repo, because it will be an overhead to build **all** the packages from Void's repo. I was thinking if we could modify `xbps-query` to ignore nonfree packages from our your-freedom denylist to show up on search results.

I think my solution of mirroring only free packages from the main repo with rsync will work. We will then only use our repo.

**Comment by reback00** [comment]
Will we be able to exclude nonfree items from search results this way? I didn't check how xbps-query works, but I think we may have to update repodata or something according to what we let in from Void mirrors (and what we don't).

**Comment by drake-newell** [comment]
Ah, you're right. I'll have reposync run `xbps-rindex -c` after syncing to update the repodata.
EDIT: I just ran `xbps-rindex`, see if you can search for `linux-firmware`.

**Comment by drake-newell** [comment]
Resolved.

**Comment by reback00** [comment]
> Ah, you're right. I'll have reposync run `xbps-rindex -c` after syncing to update the repodata.
> EDIT: I just ran `xbps-rindex`, see if you can search for `linux-firmware`.

I can see `linux-firmware` on my search results. `firefox` too. Would I have to do anything else on my end? Update some package or something?

**Comment by drake-newell** [comment]
Force update xbps and base-files specifying the repo as https://ymirlinux.org/libre with the -R flag

**Comment by reback00** [comment]
Tried:

```
sudo xbps-install -R https://ymirlinux.org/libre -f xbps base-files
```

Still shows `firefox`

**Comment by drake-newell** [comment]
> Tried:
> 
> ```
> sudo xbps-install -R https://ymirlinux.org/libre -f xbps base-files
> ```
> 
> Still shows `firefox`

Try it now.

**Comment by reback00** [comment]
It worked. Thanks.

I think now we're 100% libre, right? :100:

**Comment by drake-newell** [comment]
> It worked. Thanks.
> 
> I think now we're 100% libre, right? :100: 

Yes and no. We're 100% libre, but now we're missing some stuff. I had to exclude the debug packages from the mirror because of space constraints. I'm not sure what to do about that.
