### ISSUE TITLE
your-freedom can't be installed with xorg-fonts installed

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#30]
It conflicts with `font-bh-ttf` which is required by `xorg-fonts`. As far as I know xorg can't run without `xorg-fonts`. So this wouldn't let me install `your-freedom` on practically any machine in the world with xorg! Only way I found is to add font-bh-ttf temporarily to allowlist.txt and then install your-freedom.

But this has to be fixed. We'd have to liberate `xorg-fonts`.

**Comment by drake-newell** [comment]
I can remove it from the xorg-fonts dependencies, although I hope that wouldn't break anything. How necessary do you think font-bh-ttf is?

**Comment by reback00** [comment]
> How necessary do you think font-bh-ttf is?

Not sure. I think we would need to test on a fresh minimal environment to find out if it works without it. Testing on `xterm` would be needed for sure if possible with various font size configs. Plus, if possible on other pure xorg apps (maybe twm or something?)

I ran `./xbps-src install font-bh-ttf` and it seems to install all "Luxi *" fonts. It's [license](https://www.fontsquirrel.com/fonts/Luxi-Mono#eula) doesn't allow modification. So it's nonfree, so we can't liberate the package in any way. The fonts are ttf fonts. But seeing [Arch PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/font-bh-ttf/trunk/PKGBUILD) they use `xorg-mkfontscale`. I'm not sure if that does something special to the fonts to be used in basic xorg environment. If it does and removing it breaks something, we may have to look into that tool.

If we look into `xorg-fonts`, there are many nonfree fonts as deps, such as `font-bh-lucidatypewriter-100dpi`, `font-adobe-utopia-75dpi`. I'm not sure about these `-*dpi` fonts either what it's all about. But the package has `dejavu-fonts-ttf` and I think that should be enough on most situations. But will have to test just in case.

**Comment by drake-newell** [comment]
Odd. It looks like despite your-freedom conflicting with it, I was looking at the xorg fonts from Parabola and they have font-bh as well. Maybe it's nothing to worry about, or else they have a patch for it.

**Comment by reback00** [comment]
I couldn't find any package with the reference. As much as I searched `font-bh-ttf` [does not seem to exist](https://www.parabola.nu/packages/?sort=&q=font-bh-ttf&maintainer=&flagged=) on Parabola. Which package did you find it in?

btw... I've pushed a [commit](https://github.com/ymir-linux/void-packages/commit/fa9f6e5474f5fe7a2690faa1114425a6a45923ce) for removing nonfree fonts from xorg-fonts. I didn't test it on a real install though. Figured it also had `-75dpi`,`-100dpi`,`-type1` variations of bitstream. So it should be ok.

I'll test soon but please test on your end too if possible. xorg may behave differently on different hardware, who knows. :)

**Comment by drake-newell** [comment]
I found the reference in xorg-fonts-type1. In the files section it includes LICENSE.font-bh-type1. In xorg-fonts-100dpi, there's a similar LICENSE.font-bh. From this I would infer that Parabola includes font-bh. Also I would probably suggest that we be more cautious with this package before we go making commits as this may be unnecessary and could probably break some stuff.
EDIT: nevermind, I found the license, definitely not free. Hopefully it won't break anything.

**Comment by drake-newell** [comment]
I just build the new xorg-fonts package, so far no problems.

**Comment by reback00** [comment]
Don't worry. All the variations that were on font-bh are also available with bitstream. With bitstream variations intact, it'll be ok. In case anything goes wrong, we can revert back.

I've tested on my Thinkpad machine. No problems so far.
