### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by drake-newell** [ymir-linux/void-packages#31]
Our domain ymirlinux.org is not currently working properly. We have opened a ticket with our provider and are awaiting a response. Until further notice, replace `https://ymirlinux.org` in the files beginning with `00-` and `10-` in `/usr/share/xbps.d` with `http://198.255.68.182`.

**Comment by Konpaku-LVX** [comment]
nice

**Comment by TheIceCubeDude** [comment]
Any update on this?

**Comment by Konpaku-LVX** [comment]
i think he abandoned the project

**Comment by TheIceCubeDude** [comment]
Oh ok :(

**Comment by Konpaku-LVX** [comment]
there is hyperbola as an alternative, if you are looking for a minimal libre distro and dont want to use trisquel or parabola

**Comment by Konpaku-LVX** [comment]
its also systemd free iirc

**Comment by Konpaku-LVX** [comment]
parabola lets you use OpenRC but i never got parabola to work with OpenRC before but your results may vary

**Comment by TheIceCubeDude** [comment]
Yeah, I've considered it but i prefer XBPS to pacman, and also something a bit more independent. I've manually installed linux-libre on my void installation, and I consider it 'free' enough. Thanks, though.

**Comment by Konpaku-LVX** [comment]
nice, glad you could figure something you like out

**Comment by drake-newell** [comment]
Project is indeed abandoned.
