### ISSUE TITLE
Option to run on tty (alternative to dmenu)

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#4]
dmenu is ok and all. But implementing a terminal-only selection option would be wonderful. Then we can logout from x11 session, stop dm service (if any) and run the build process from tty. I guess this should reduce the stress on the machine a little bit when building.

Possible solution could be to print all options on terminal with a corresponding number and ask for input. Implementing something simple like [this](https://askubuntu.com/a/1716) would reduce our dependencies.

There is also [dialog solution](https://askubuntu.com/a/666179) on that page. But having a dialog selection for one thing only and the rest being CLI is maybe not the consistent thing to do. (Maybe later, who knows? ;) )

**Comment by drake-newell** [comment]
I like the interactive/fuzzy features of dmenu, but you're probably right. Maybe a switch to fzf would work? I'll do the same thing I did for xtools to check for/install fzf

**Comment by drake-newell** [comment]
Just switched to fzf
