### ISSUE TITLE
We can use shallow clone for the script

### ISSUE THREAD

**Issue by reback00** [ymir-linux/void-packages#5]
The script clones this repository including all its past change history and branches:
https://github.com/drake-newell/void-packages/blob/5a089025729cc137ff7b08b2e3dc32c3bbf625c4/void-liberation-local#L18

I think we can use [shallow clone](https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones) for making it faster, because we won't need all those history for building:
```
git clone --depth 1 https://github.com/drake-newell/void-packages.git
```

**Comment by drake-newell** [comment]
Added it.
